server.port=1992
spring.profiles.active=dev
spring.application.name=core-service

api.external.privateKey=2w0YuHm6FM58eD5T6wgdAarQ8ZiWBzZS
api.external.addressBaseUrl=

# FOR MYSQL
#spring.datasource.url=jdbc:mysql://125.212.193.14:3306/manager_python?useUnicode=yes&characterEncoding=UTF-8
#spring.datasource.username=root
#spring.datasource.password=duyanh90

#spring.datasource.url=jdbc:mysql://210.211.101.50:3306/manager_python_v2?useUnicode=yes&characterEncoding=UTF-8
#spring.datasource.username=acc_python
#spring.datasource.password=Usa@Vietnam2021

#MySQL config
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#FOR SQL SERVER
spring.datasource.url=jdbc:sqlserver://10.19.10.159;databaseName=Verify3CX
spring.datasource.username=sales
spring.datasource.password=Hero236$
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect

spring.jpa.properties.hibernate.connection.characterEncoding=utf-8 
spring.jpa.properties.hibernate.connection.CharSet=utf-8 
spring.jpa.properties.hibernate.connection.useUnicode=true 

spring.jpa.properties.hibernate.dialect.storage_engine=innodb
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#logging.file.name=canva.log

spring.thymeleaf.prefix=classpath:/templates/

api.secretKey=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ0.eyJhdWQiOlsicmVzb3VyY2VfaWQiXSwidXNlcl9uYW1lIjoibGFwLnAudC5jLnJAZ21haWwuY29tIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIiwidHJ1c3QiXSwiaWQiOjUxMCwiZXhwIjoxNjMwOTg0NDU4LCJhdXRob3JpdGllcyI6WyJST0xFX1RFQUNIRVIiXSwianRpIjoiYjA5MzAwMDEtYjFkNi00NTI4LWIwMjQtYzI4MWM0OGUyNTNjIiwiY2xpZW50X2lkIjoiY29yZS1hcGktY2xpZW50In1.9jPrXN0XLRiWH6ijPc505hapFzfbDR4PXIrgQChzb42

#https://stackoverflow.com/questions/36451620/hibernate-field-naming-issue-with-spring-boot-naming-strategy
#Fix : com.microsoft.sqlserver.jdbc.SQLServerException: The column name
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
