package com.java.enums;

/**
 * Created by hoangnm on 1/14/20.
 */

/**
 * value format: serviceCode_Number, ex: service schoolly core has code: SCLC: SCLC-001
 */
public enum ErrorCode {
    /* Common Error, should use same for all services */
    UNKNOWN("SCLCOM_UKN", "Something went wrong. Please try again"),
    NO_ERROR("SCLCOM_000", "No error occurred"),
    INVALID_PARAMETERS("SCLCOM_0001", "Invalid parameters"),
    INVALID_ACCESS_TOKEN("SCLCOM_0002", "Invalid access token"),
    INVALID_CONTENT_EXCEL("SCLCOM_0003", "Invalid content in excel file"),

    BAD_CREDENTIAL("SCLCOM_1000", "Bad credentials"),
    USER_NOT_FOUND("SCLCOM_1001", "User not found"),
    USER_LOCKED("SCLCOM_1002", "User locked"),
    USER_INACTIVE("SCLCOM_1003", "User inactive"),


    RECAPTCHA_ERROR("SCLCOM_2000", "Verify ReCaptcha error"),
    RECAPTCHA_BOT_DETECTED("SCLCOM_2001", "You are like a bot. No permission to perform action"),

    PAGE_SIZE_MUST_GREATER_OR_EQUAL_ONE("SCLCOM_3000", "Page is greater or equal 1"),
    SIZE_MUST_GREATER_OR_EQUAL_ONE("SCLCOM_3001", "Size is greater or equal 1"),


    // Elearning Error
    ELEARNING_NOT_FOUND("SCLC_001", "Elearning not found or permission access denied"),
    SUBJECT_NOT_FOUND("SCLC_002", "Subject not found"),
    LEVEL_NOT_FOUND("SCLC_003", "Level not found"),
    ELEARNING_TYPE_INVALID("SCLC_004", "Elearning type invalid"),

    INVALID_PARAM("SCLC_006", "Invalid param"),
    CHAPTER_NOT_FOUND("SCLC_007", "Chapter not found or permission access denied"),
    ERROR_SAVE_DATABASE("SCLC_008", "Cannot save to database"),
    LESSON_NOT_FOUND("SCLC_009", "Lesson not found or permission access denied"),
    FILE_INVALID_FORMAT("SCLC_0010", "File invalid format"),
    DOC_INVALID_FORMAT("SCLC_0011", "Document file invalid format"),
    UPLOAD_FAIL("SCLC_0012", "Upload file failed"),
    LESSON_DOC_NOT_FOUND("SCLC_0013", "Lesson doc not found or permission access denied"),
    PERMISSION_DENIED("SCLC_0014", "Permission denied"),
    EXERCISE_NOT_FOUND("SCLC_0015", "Exercise not found or permission access denied"),
    QUESTION_NOT_FOUND("SCLC_0016", "Question not found or permission access denied"),
    INVALID_QUESTION_TYPE("SCLC_0017", "Invalid question type"),
    ANSWER_PARAM_INDEX_REQUIRED("SCLC_0018", "Index or Correct param required"),
    ANSWER_NOT_FOUND("SCLC_0019", "Answer not found or permission access denied"),
    QUESTION_HAVE_ANSWER_INDEX_EXISTED("SCLC_0020", "Question have answer index existed"),
    QUESTION_HAVE_ANSWER_CORRECT_EXISTED("SCLC_0021", "Question have answer correct existed"),
    ELEARNING_FEE_OR_DISCOUNT_NOT_NEGATIVE_NUMBER("SCLC_0022", "Fee or price required greater or equal minimum price (default: 10.000 VND)"),
    EXERCISE_HAVE_QUESTION_INDEX_EXISTED("SCLC_0023", "Question index existed in exercise"),
    ELEARNING_HAVE_CHAPTER_INDEX_EXISTED("SCLC_0024", "Chapter index existed in elearning"),
    ELEARNING_HAVE_CHAPTER_NAME_EXISTED("SCLC_0025", "Chapter name existed in elearning"),
    LESSON_HAVE_LESSON_DOC_NAME_EXISTED("SCLC_0026", "Lesson doc name existed in lesson"),
    ELEARNING_HAVE_EXERCISE_NAME_EXISTED("SCLC_0027", "Exercise name existed in elearning"),
    TEST_NOT_FOUND("SCLC_0028", "Test not found or permission access denied"),
    TEST_ATTACHMENT_NOT_FOUND("SCLC_0029", "File upload not found or deleted"),
    TEST_METHOD_NOT_SUPPORT("SCLC_0030", "Test method not support. Only support IPTEST | MANUAL | UPLOAD"),
    TEST_NOT_SUPPORT_ADD_QUESTION("SCLC_0031", "Not support add question to test. Only add question with test type = MANUAL. Only upload question with test type = UPLOAD. Only import question from test with test type = IPTEST. Please check test method again"),
    TEST_NOT_ALLOW_UPDATE("SCLC_0032", "Test not allow update"),
    TEST_STATUS_NOT_ALLOW_STUDY("SCLC_0033", "Test status not allow to study"),
    TEST_TYPE_NOT_ALLOW_STUDY("SCLC_0034", "Test type not allow to study"),
    EXAM_IS_NOT_APPROVED("SCLC_0035", "Exam is not approved"),

    ONLINE_CLASS_NOT_FOUND("SCLC_0128", "Online class not found"),
    ONLINE_CLASS_NEED_HAS_AT_LEAST_ONE_SCHEDULE_TO_ENABLE("SCLC_0129", "Online class need has at least one schedule to set enable to true"),
    ONLINE_CLASS_SEARCH_TYPE_NOT_FOUND("SCLC_0130", "Search type not found"),
    ONLINE_CLASS_INVITATION_NOT_FOUND("SCLC_0131", "Invitation to join online class not found"),
    ONLINE_LESSON_NOT_FOUND("SCLC_0132", "Online lesson not found"),
    ONLINE_CLASS_ATTENDANCE_NOT_FOUND("SCLC_0133", "Status attendance of user not found"),
    ONLINE_LESSON_HAS_EXISTED("SCLC_0134", "Online lesson has existed"),
    ZOOM_ERROR_QUERY("SCLC_0135", "Error when try to use zoom api"),
    ONLINE_SESSION_NOT_FOUND("SCLC_0136", "Online session not found"),
    MEETING_CAN_NOT_HOSTED_BY_ANY_ACCOUNT("SCLC_0137", "Can not hosted meeting in this time, may be a room has hosted by this email"),
    ONLINE_CLASS_STUDENT_HAS_BANNED("SCLC_0138", "Student has banned"),
    ONLINE_CLASS_STUDENT_HAS_NOT_BANNED("SCLC_0139", "Can not un banned student. This student has not banned"),
    ONLINE_CLASS_STREAMING_CAN_NOT_UPDATE("SCLC_0140", "Can not update this online class, this class is streaming"),
    STUDENT_CAN_NOT_VIEW_SCHEDULE_BECAUSE_NOT_INVITED("SCLC_0141", "You must invited to view schedule of this online class"),
    ONLINE_CLASS_DUPLICATE_SCHEDULE("SCLC_0142", "Duplicate time schedule. Please check and update available schedule again"),
    ONLINE_LESSON_STREAMING_NOT_FOUND("SCLC_0143", "Can not found any lesson streaming"),
    DO_NOT_HAVE_ANY_STUDENT_TO_INVITE("SCLC_0144", "You must add at least one student to send invitation"),
    ELEARNING_HAVE_MAXIMUM_ONE_ONLINE_CLASS("SCLC_0145", "Elearning had online class. You only can create maximum 1 online class in each elearning"),
    NOT_INVITED_TO_ONLINE_CLASS("SCLC_0141", "You must invited to join this online class"),
    ONLINE_CLASS_NOT_STREAMING("SCLC_0142", "Online class not streaming"),
    CAN_NOT_DELETE_ONLINE_CLASS_STREAMING("SCLC_0143", "Can not delete online class is streaming"),
    CAN_NOT_DELETE_SCHEDULE_IS_STREAMING("SCLC_0145", "Can not delete schedules, some online class is streaming or finished with those schedules"),
    CAN_NOT_UPDATE_LESSON_IS_STREAMING("SCLC_0146", "Online class is streaming, can not update this lesson online"),
    CAN_NOT_UPDATE_LESSON_IS_FINISHED("SCLC_0147", "Lesson is finished, can not update this lesson online"),
    CAN_NOT_UPDATE_LESSON_HAS_CLASS_STREAMING("SCLC_0148", "Online class is streaming, can not update this lesson online"),
    CAN_NOT_ATTENDANCE_BECAUSE_NOT_JOIN_TO_ELEARNING("SCLC_0149", "You must join to elearning before."),
    STUDENT_NOT_INVITED_TO_ONLINE_CLASS("SCLC_0150", "Student has not invited in this online class"),
    TIME_NOT_AVAILABLE_TO_ATTENDANCE("SCLC_0151", "Over time to attendant"),
    HAS_ATTENDANT_BEFORE("SCLC_0152", "You attendant this lesson before."),
    CAN_NOT_CREATE_LESSON_HAS_START_TIME_IN_PAST("SCLC_0153", "Thời gian của lịch học phải lớn hơn thời gian hiện tại"),
    SCHEDULE_MUST_HAS_AT_LEAST_ONE_LESSON("SCLC_0154", "This schedule not have any lesson"),
    TIME_TABLE_NOT_SUPPORTED_VIEW_TYPE("SCLC_0155", "Not supported this type for view time table"),
    END_TIME_ONLINE_CLASS_MUST_LESS_OR_EQUAL_THAN_END_TIME_ELEARNING("SCLC_0156", "Thời gian kết thúc của phòng học online không được vượt quá thời gian kết thúc của bài giảng/khóa học"),

    USER_VOTED_ELEARNING_EXIST("SCLC_0037", "You voted this elearning before"),
    EXERCISE_HAVE_QUESTION_NAME_EXISTED("SCLC_0038", "Question name existed in exercise"),
    ELEARNING_HAVE_LESSON_NAME_EXISTED("SCLC_0039", "Lesson name existed in elearning"),
    REPOSITORY_FILE_NOT_FOUND("SCLC_0040", "Repository file not found or permission access denied"),
    CANNOT_DELETE_FILE("SCLC_0041", "Cannot delete file. You do not permission or file not exist"),
    NOT_HAVE_ANY_ELEARNING_IN_CART("SCLC_0042", "You not have any elearning in cart. Please add at least one item to your cart"),
    CART_ITEM_NOT_FOUND("SCLC_0043", "Elearning not add to cart before or has been deleted"),
    ELEARNING_WAS_ADD_OR_BOUGHT("SCLC_0044", "Elearning was add to cart or bought"),
    CART_ITEM_PRICE_NOT_CORRECT("SCLC_0045", "Cart item has not correct price"),
    CART_ORDER_NOT_FOUND("SCLC_0046", "Order not found or deleted"),
    ELEARNING_WAS_ADD("SCLC_0047", "Elearning was add to cart"),
    CART_ITEMS_NOT_ADD_TO_CART_BEFORE("SCLC_0048", "Some cart items has not add to cart before"),
    MISSING_PAYMENT_REQUEST("SCLC_0049", "Missing payment request"),
    ELEARNING_WAS_BOUGHT("SCLC_0050", "Elearning was bought before"),
    CART_ORDER_WAS_PAID("SCLC_0051", "Order had been paid"),

    MARK_REQUIRED("SCLC_0052", "Required mark for exercise"),
    MARK_INVALID("SCLC_0053", "Invalid mark for exercise"),
    EXERCISE_EVALUATED("SCLC_0054", "This exercise is evaluated"),
    USER_ID_OR_STUDENT_ID_REQUIRED("SCLC_0055", "user_id or student_id is required"),
    EXERCISE_NOT_WORKED("SCLC_0056", "This user have not done this exercise"),
    EXERCISE_REQUIRED_NOT_WORKED("SCLC_0057", "You must complete all required exercises for this lesson"),
    EXERCISE_MAX_REWORK("SCLC_0058", "This exercise exceeded the number of rework"),
    EXERCISE_INVALID_STATUS("SCLC_0059", "This status of exercise is invalid"),

    CART_ORDER_IS_EMPTY("SCLC_0060", "Cart order is empty. Last order is waiting for repay or not found"),
    ELEARNING_WAS_HIDDEN("SCLC_0061", "Elearning was hidden, can not add to cart"),

    TEACHER_CAN_NOT_BUY_ELEARNING_OF_THEM("SCLC_0062", "Can not buy your elearning"),
    EXERCISE_WAIT_UTIL_OPEN_TIME("SCLC_0063", "This exercise has not yet begun"),
    EXERCISE_OVER_CLOSE_TIME("SCLC_0064", "This exercise is closed"),
    EXERCISE_OVER_DURATION("SCLC_0065", "Working time is over duration of this exercise"),
    EXERCISE_PASSED("SCLC_0066", "This exercise is passed"),
    TEACHER_CAN_NOT_BUY_EXAM_OF_THEM("SCLC_0067", "Can not buy your exam"),
    EXERCISE_MUST_START("SCLC_0068", "Test must be started"),

    // School Error
    SCHOOL_NOT_FOUND("SCLC_1028", "School not found or deleted"),
    GRADE_NOT_FOUND("SCLC_1029", "Grade not found"),
    CLASS_NOT_FOUND("SCLC_1030", "Class not found or deleted"),
    STUDENT_NOT_FOUND("SCLC_1031", "Student not found, deleted or disable"),
    PROFESSION_GROUP_NOT_FOUND("SCLC_1032", "Profession group not found"),
    TEACHER_NOT_FOUND("SCLC_1033", "Teacher not found or deleted"),
    PROFESSION_GROUP_EXISTED("SCLC_1034", "Profession group existed"),
    ALREADY_ACCOUNT_LINKED("SCLC_1036", "Already have an account linked"),

    CODE_NOT_FOUND("SCLC_1037", "Code not found"),
    PROVINCE_NOT_FOUND("SCLC_1038", "Province not found"),
    DISTRICT_NOT_FOUND("SCLC_1039", "District not found"),
    WARD_NOT_FOUND("SCLC_1040", "Ward not found"),

    RESIZE_IMAGE_FAIL("SCLC_1041", "Resize image fail"),
    GET_URL_RESIZE_IMAGE_FAIL("SCLC_1042", "Cannot get url resize image"),
    IMAGE_URL_FAIL("SCLC_1043", "Cannot get image url"),

    ACTION_INVALID("SCLC_1041", "Action invalid"),
    ELEARNING_TYPE_NOT_SUPPORT("SCLC_1042", "Type elearning invalid. Only support : COURSE|LECTURE"),
    ELEARNING_STATUS_PERMISSION("SCLC_1043", "Status of Elearning in not edit permission. Only status: PENDING have permission edit"),
    LESSON_TYPE_NOT_SUPPORT("SCLC_1044", "Lesson type not support. Only support: (VIDEO | ARTICLE | PDF | DOC | TXT)"),
    LESSON_UPLOAD_ARTICLE_FAIL("SCLC_1045", "Upload article lesson file failed"),
    ELEARNING_LECTURE_ONLY_SUPPORT_ONE_LESSON("SCLC_1046", "Elearning have type LECTURE only support one lesson"),
    ELEARNING_LECTURE_NOT_IN_CHAPTER("SCLC_1047", "Elearning have type LECTURE not in chapter"),
    ELEARNING_COURSE_REQUIRED_IN_CHAPTER("SCLC_1047", "Elearning have type COURSE required in chapter"),
    CHAPTER_NOT_IN_ELEARNING("SCLC_1048", "Chapter not in elearning"),
    ELEARNING_HAVE_LESSON_INDEX_EXISTED("SCLC_1049", "Lesson index existed in chapter"),
    LESSON_NAME_EXISTED_IN_CHAPTER("SCLC_1050", "Lesson name existed in chapter"),
    ELEARNING_LECTURE_NOT_ALLOW_INDEX("SCLC_1051", "Elearning have type LECTURE not in allow index"),
    LESSON_DOC_OR_URL_REQUIRED("SCLC_1052", "Lesson doc file or Url file required"),
    LESSON_DOC_FORMAT_REQUIRED("SCLC_1053", "Lesson doc file required format file"),
    URL_FILE_INVALID("SCLC_1054", "Url file invalid"),
    URL_FILE_NOT_COMPATIBLE_FORMAT_INPUT("SCLC_1055", "File choose not compatible with format input"),
    ELEARNING_COURSE_REQUIRED_IN_INDEX("SCLC_1056", "Elearning have type COURSE required index param"),
    EXERCISE_REQUIRED_DURATION_OR_REWORKS("SCLC_1057", "Exercise required duration & reworks"),
    INVALID_EXERCISE_TYPE("SCLC_1058", "Invalid exercise/test type"),
    LESSON_HAVE_EXERCISE_NAME_EXISTED("SCLC_1059", "Exercise name existed in Lesson"),
    LESSON_HAVE_EXERCISE_INDEX_EXISTED("SCLC_1060", "Exercise index existed in Lesson"),
    LESSON_REQUIRED_ARTICLE("SCLC_1061", "Lesson required ARTICLE type"),
    CANNOT_DELETE_ELEARNING_ARCHIVE("SCLC_1062", "Cannot delete archive elearning. You do not permission or your elearning not exist"),
    USER_ELEARNING_NOT_PERMISSION("SCLC_1063", "You do not permission access elearning"),

    INVALID_EXERCISE_CATEGORY("SCLC_1064", "Invalid exercise category"),
    EXERCISE_PASS_SCORE_REQUIRED("SCLC_1065", "Exercise pass score required"),
    ELEARNING_BENEFIT_INVALID_FORMAT("SCLC_1066", "Benefit invalid format. Required json"),
    ELEARNING_TYPE_NOT_CHANGE("SCLC_1067", "Elearning type is not change (For case update)"),
    ELEARNING_PUBLISH_ERROR_GENERAL("SCLC_1068", "Cannot publish this elearning. Because elearning general is not complete"),
    ELEARNING_PUBLISH_ERROR_CONTENT("SCLC_1069", "Cannot publish this elearning. Because elearning have content is not complete"),
    ELEARNING_PUBLISH_ERROR_SETTING("SCLC_1070", "Cannot publish this elearning. Because elearning setting is not complete"),
    ELEARNING_PUBLISH_ERROR_COMPLETE("SCLC_1071", "This elearning was publish completed before. You do not publish it"),
    ELEARNING_LECTURE_NOT_HAVE_CHAPTER("SCLC_1072", "Elearning have type = LECTURE not have chapter"),
    ELEARNING_PUBLISH_ERROR_STATUS("SCLC_1073", "Status of Elearning invalid. Only status: PENDING have permission publish"),
    INDEX_MUST_GREATER_OR_EQUAL_ONE("SCLC_1074", "Index is greater or equal 1"),
    QUESTION_IN_EXERCISE_TEST_REQUIRED_SCORE("SCLC_1075", "Question required points"),
    SCORE_MUST_GREATER_OR_EQUAL_ZERO("SCLC_1076", "Point is greater  0"),
    TOTAL_SCORE_EXCEED_MAX_SCORE("SCLC_1077", "Total points in exercise exceed 10"),
    ANSWER_REQUIRED("SCLC_1078", "Required answer for question"),
    QUESTION_HAVE_ESSAY_ONLY_ONE_ANSWER("SCLC_1079", "Question have type ESSAY only have one answer"),
    ANSWER_PARAM_CORRECT_REQUIRED("SCLC_1080", "Required correct in answer"),
    ANSWER_PARAM_CONTENT_REQUIRED("SCLC_1081", "Required content in answer"),
    REQUIRED_AT_LEAST_ONE_CORRECT_ANSWER_IN_QUESTION("SCLC_1082", "Required at least one correct answer in question"),
    ONLY_ONE_CORRECT_ANSWER_IN_QUESTION_CHOICE("SCLC_1083", "Only accept one correct answer in question have type CHOICE"),
    ONLY_ONE_ANSWER_IN_QUESTION_TYPE_ESSAY("SCLC_1084", "Only accept one answer in question have type Essay"),
    ANSWER_NOT_ACCEPT_INDEX_VALUE("SCLC_1085", "Answer not accept index value"),
    REPOSITORY_CAPACITY_LOCKED("SCLC_1086", "Your capacity is locked. Please contact admin to unlocked"),
    REPOSITORY_CAPACITY_USED_EXCEED_MAX_CAPACITY("SCLC_1087", "Your used capacity is exceed max capacity. Please contact admin to unlocked"),
    REPOSITORY_CAPACITY_MAX_NO_SETTING("SCLC_1088", "Your max capacity is no setting. Please contact admin to unlocked"),
    REPOSITORY_CAPACITY_NOT_FOUND("SCLC_1089", "Repository capacity not found or permission access denied"),
    INVALID_TESTING_CATEGORY("SCLC_1090", "Invalid testing category"),
    INVALID_TESTING_TYPE("SCLC_1091", "Invalid testing type"),
    INVALID_TESTING_PARENT("SCLC_1092", "Invalid testing parent"),
    TESTING_NAME_REQUIRED("SCLC_1093", "name is required"),
    TESTING_GRADE_ID_REQUIRED("SCLC_1094", "grade_id is required"),
    TESTING_SUBJECT_ID_REQUIRED("SCLC_1095", "subject_id is required"),
    TESTING_PARENT_ID_REQUIRED("SCLC_1096", "parent_id is required"),
    TESTING_CLASS_AND_GROUP_NOT_NULL("SCLC_1097", "You must assign at least one class or group"),
    TESTING_INVALID_SUBMISSION_TYPE("SCLC_1098", "Invalid submission type"),
    TESTING_QUESTION_UPLOAD_NOT_ALLOW("SCLC_1099", "Upload file are not accepted for this question"),

    ORGANIZATION_NOT_FOUND("SCLC_2001", "Organization not found or deleted"),
    SCHOOL_TYPE_NOT_SUPPORT("SCLC_2002", "School type not support"),
    STAFF_DUTY_NOT_FOUND("SCLC_2003", "Staff duty not found or deleted"),
    ORGANIZATION_TYPE_NOT_FOUND("SCLC_2004", "Organization type not found"),
    STAFF_NOT_FOUND("SCLC_2005", "Staff not found or deleted"),
    SCHOOL_YEAR_NOT_FOUND("SCLC_2006", "School year not found or deleted"),
    GRADE_EXISTED("SCLC_2007", "Grade existed"),
    SUBJECT_TYPE_INVALID("SCLC_2008", "Subject type invalid"),
    SUBJECT_FORM_INVALID("SCLC_2009", "Subject form invalid"),
    TEACHER_CLASS_NOT_FOUND("SCLC_2010", "Teacher class not found"),
    PARENT_NOT_FOUND("SLCL_2011", "Parent not found"),
    ROLE_NOT_FOUND("SLCL_2012", "Role not found"),
    CLASS_HAVE_HOMEROOM_TEACHER_ALREADY("SLCL_2013", "Class have homeroom teacher already"),
    TEACHER_IS_NOT_THE_HOMEROOM_TEACHER_OF_CLASS("SLCL_2014", "Teacher is not the homeroom teacher of class"),
    ORGANIZATION_ADMINISTRATOR_NOT_FOUND("SLCL_2015", "Organization administrator not found"),
    FEE_INVALID("SLCL_2016", "Fee invalid"),
    SUBJECT_CODE_EXISTED("SLCL_2017", "Subject code existed"),
    USER_ELEARNING_NOT_FOUND("SCLC_2018", "User elearning not found"),
    ELEARNING_REQUEST_NOT_FOUND("SCLC_2019", "Elearning request not found"),
    ELEARNING_REQUEST_EXISTED("SCLC_2020", "Your request has been sent"),
    HOMEROOME_OTHER_CLASS("SCLC_2021", "This teacher is homeroom of other class"),
    FROMDATE_GREATER_THAN_TODATE("SCLC_2022", "From date greater than to date"),
    CREATE_ORG_ADMIN_FALSE("SCLC_2023", "Create org admin false"),
    INVALID_PASSWORD("SCLC_2024", "Invalid password"),
    USER_EXISTED("SCLC_2025", "User existed"),
    REQUEST_JOIN_ELEARNING_YOURSELF("SCLC_2026", "Request join elearning of yourself"),
    SCHOOL_MUST_HAVE_AT_LEAST_2_SCHOOL_YEAR_TO_TRANSFER_STUDENT("SCLC_2027", "School must have at least 2 schoolyear to transfer student"),
    OTHER_USER_HAVE_ALREADY_LINKED_THIS_CODE("SCLC_2028", "Other user have already linked to this code"),
    ACCOUNT_HAVE_ALREADY_LINKED("SCLC_2029", "Account have already linked"),
    EXAM_COMMENT_NOT_FOUND("SCLC_2030", "Exam comment not found or deleted"),
    EXAM_ANNOUNCEMENT_NOT_FOUND("SCLC_2031", "Exam announcement not found or deleted"),
    ORGANIZATION_SHORT_CODE_EXISTED("SCLC_2032", "Organization short code existed"),

    PASS_CODE_INVALID("SCLC_1090", "Passcode invalid"),
    INTERACTIVE_QUESTION_NOT_FOUND("SCLC_1091", "Interactive question not found or permission access denied"),
    PASSCODE_REQUIRED("SCLC_1092", "Passcode required"),
    DISCOUNT_GREATER_FEE("SCLC_1092", "Price cannot greater fee"),
    ELEARNING_PRIVACY_INVALID("SCLC_1093", "Elearning privacy invalid"),
    ELEARNING_STATUS_NOT_ALLOW_EDIT("SCLC_1094", "Elearning was published, you do not permission update or delete"),
    ANNOUNCEMENT_NOT_FOUND("SCLC_1095", "Announcement not found or permission access denied"),
    ROLE_ACCESS_DENIED("SCLC_1096", "Your role is not allow access"),
    REQUIRED_TO_DATE_PARAM("SCLC_1097", "Required to_date params"),
    REQUIRED_FROM_DATE_PARAM("SCLC_1098", "Required from_date params"),
    INVALID_DATE_PARAMS("SCLC_1099", "Invalid date param .Required format yyyy-MM-dd"),
    PASS_SCORE_LESS_MINIMUM("SCLC_1100", "Pass score less minimum score"),
    DURATION_LESS_MINIMUM("SCLC_1101", "Duration less minimum time"),
    REWORKS_LESS_MINIMUM("SCLC_1102", "Reworks less minimum"),
    EXCEED_MAX_ANSWER_IN_QUESTION("SCLC_1103", "Exceed max answer in question type choice"),
    ELEARNING_PUBLISH_ERROR_EXERCISE("SCLC_1104", "Cannot publish this elearning. Because elearning have exercise is not complete"),
    ELEARNING_PUBLISH_ERROR_TEST("SCLC_1105", "Cannot publish this elearning. Because elearning have test is not complete"),
    LESS_MIN_ANSWER_IN_QUESTION("SCLC_1106", "Less min answer in question have type choice"),
    CANNOT_DELETE_ELEARNING("SCLC_1107", "Cannot delete elearning. You do not permission or your elearning not exist"),
    CANNOT_HIDDEN_ELEARNING("SCLC_1108", "Cannot make hidden/unhidden elearning. You do not permission or your elearning not exist"),
    ELEARNING_IS_HIDDEN_BEFORE("SCLC_1109", "Cannot make hidden elearning. These was hidden before"),
    ELEARNING_IS_RESTORE_BEFORE("SCLC_1110", "Cannot make restore elearning. These was restore before"),
    ELEARNING_IS_HIDDEN_BY_ADMIN("SCLC_1111", "Cannot make restore elearning. These was hidden by admin, you do not restore them"),
    CANNOT_REMOVE_ELEARNING_FAVOURITE("SCLC_1112", "Cannot remove favourite elearning. You do not permission or your elearning not exist"),
    ELEARNING_IS_ARCHIVE_BEFORE("SCLC_1113", "Cannot make archive elearning. These was archive before"),
    ELEARNING_IS_FAVOURITE_BEFORE("SCLC_1114", "Cannot make favourite elearning. These was favourite before"),
    ELEARNING_HAVE_TEST_INDEX_EXISTED("SCLC_1115", "Test index existed in elearning"),
    OPEN_TIME_FOR_TEST_INVALID("SCLC_1116", "Open time for the test is invalid"),
    CANNOT_UPDATE_CATEGORY_EXERCISE("SCLC_1117", "Cannot update category exercise or test"),
    INVALID_DATE_TIME_PARAMS("SCLC_1118", "Invalid date param .Required format yyyy-MM-dd HH:mm:ss"),
    PAYMENT_TYPE_NOT_SUPPORT("SCLC_1119", "This payment type not supported"),
    SECURE_HASH_INVALID("SCLC_1120", "Secure hash invalid"),
    TRANSACTION_NOT_FOUND("SCLC_1121", "Transaction not found"),
    HASH_CODE_NOT_FOUND("SCLC_1122", "Hash code not found"),
    INVALID_TYPE_IMAGE("SCLC_1123", "File required image type"),
    CAN_NOT_UPDATE_WALLET_FOR_TEACHER("SCLC_1124", "Can not update wallet for teacher"),
    CAN_NOT_UPDATE_TRANSACTION_STATUS("SCLC_1125", "Can not update transaction status."),
    CAN_NOT_SEARCH_ORGANIZATION_ANOTHER("SCLC_1126", "You do not permission search data another school"),
    ELEARNING_IS_JOIN_BEFORE("SCLC_1127", "The elearning is join before"),
    ELEARNING_IS_NOT_APPROVED("SCLC_1128", "Elearning is not approved"),
    CAN_NOT_CREATE_OR_UPDATE_ONLINE_CLASS_WITH_HIDDEN_ELEARNING("SCLC_1129", "Cannot create or update olclass with hidden elearning"),
    ANNOUNCEMENT_WAS_DELETED("SCLC_1130", "Announcement was deleted"),
    INVALID_TYPE_UPLOAD_FEEDBACK("SCLC_1131", "File required one of types: image, doc"),
    INVALID_TYPE_UPLOAD_NEWS_ATTACHMENT("SCLC_1132", "File required one of types: image, doc"),
    INVALID_TYPE_UPLOAD_NEWS_THUMB("SCLC_1133", "File required one of types: image"),
    INVALID_TYPE_UPLOAD_ANNOUNCEMENT_THUMB("SCLC_1134", "File required one of types: image"),
    INVALID_TYPE_UPLOAD_ANNOUNCEMENT_ATTACHMENT("SCLC_1135", "File required one of types: image, doc"),
    INVALID_TYPE_UPLOAD_COVER_ORG("SCLC_1136", "File required one of types: image"),
    INVALID_TYPE_UPLOAD_LINK_WEB_LOGO("SCLC_1137", "File required one of types: image"),
    INVALID_TYPE_UPLOAD_TIMETABLE_ATTACHMENT("SCLC_1138", "File required one of types: image, doc"),
    INVALID_TYPE_ATTACHMENT("SCLC_1139", "File required one ò types: image, docs"),

    INSTANCE_USER_SERVICE_INVALID("SCLC_1150", "Do not have any user-service application registed."),
    MISSING_DEVICE_ID("SCLC_1151", "Missing device-id in request header. Format: client-info: {Device_Id: 'client_device_id'}"),
    TRANSACTION_HAS_SUCCESS("SCLC_1152", "Transaction has success, can not update"),
    TRANSACTION_HAS_FAILED("SCLC_1153", "Transaction has failed, can not update"),
    ELEARNING_APPROVED_NOT_ALLOW_EDIT_PARAM("SCLC_1154", "Elearning was published, you do not permission update privacy or startime_enable, start_time or endtime_enable, end_time"),
    ELEARNING_FEE_OR_PRICE_REQUIRED("SCLC_1155", "Fee or price requried"),
    TRANSACTION_HAS_CANCELLED("SCLC_1156", "Transaction has cancelled, can not update"),
    ORDER_HAS_BEEN_CANCELLED("SCLC_1157", "Order has cancelled, can not cancel or repay"),
    ORDER_HAS_BEEN_PAYMENT("SCLC_1158", "Order has been payment, can not cancel or repay"),
    ORDER_HAS_BEEN_FAILED("SCLC_1159", "Order has been payment failed before, can not cancel or repay"),
    DUPLICATE_FILE_NAME("SCLC_1160", "File name was existed ! Please try another name"),
    INVALID_ACTION_JOIN("SCLC_1161", "Invalid action due join only for elearning free"),
    NOT_ALLOW_JOIN_YOUR_ELEARNING("SCLC_1162", "Not allow join your elearning"),
    STATUS_NOT_ALLOW_JOIN("SCLC_1163", "Status elearning not allow join"),
    NOT_ALLOW_VOTE_YOURSELF_ELEARNING("SCLC_1165", "Do not allow vote yourself elearning"),
    DOC_EXCEED_MAX_SIZE("SCLC_1166", "Document exceed max size"),
    EXCEED_MAX_DOC_IN_LESSON("SCLC_1167", "Exceed max document in lesson"),
    REJECT_ACTION_REQUIRED_REASON("SCLC_1168", "Reject action required note param"),

    ELEARNING_REQUIRED_START_TIME("SCLC_1169", "Required start_time param"),
    ELEARNING_REQUIRED_END_TIME("SCLC_1170", "Required end_time param"),
    ELEARNING_INVALID_START_TIME("SCLC_1171", "Invalid start_time param"),
    ELEARNING_INVALID_END_TIME("SCLC_1172", "Invalid end_time param"),
    ELEARNING_REQUIRED_START_TIME_ENABLE("SCLC_1173", "Required starttime_enable param"),
    ELEARNING_REQUIRED_END_TIME_ENABLE("SCLC_1174", "Required endtime_enable param"),
    ELEARNING_END_TIME_LESS_START_TIME("SCLC_1175", "End_time must greater start_time"),
    PASS_SCORE_GREATER_MAXIMUM("SCLC_1176", "Pass score greater maximum score"),
    REQUIRED_LESSON_TYPE_SCORM("SCLC_1177", "Required lesson type SCORM"),
    INVALID_TEST_CATEGORY("SCLC_1197", "Invalid test category"),
    CLOSE_TIME_FOR_TEST_INVALID("SCLC_1179", "Close time for the test is invalid"),

    TEST_REQUIRED_OPEN_TIME_ENABLE("SCLC_1180", "Required opentime_enable param"),
    TEST_REQUIRED_CLOSE_TIME_ENABLE("SCLC_1181", "Required closetime_enable param"),
    TEST_CLOSE_TIME_LESS_OPEN_TIME("SCLC_1182", "Close_time must greater open_time"),
    TEST_REQUIRED_OPEN_TIME("SCLC_1183", "Required open_time param"),
    TEST_REQUIRED_CLOSE_TIME("SCLC_1184", "Required close_time param"),
    TEST_OPEN_TIME_NOT_VALID_RULE("SCLC_1185", "Open time invalid rule"),
    TEST_CLOSE_TIME_NOT_VALID_RULE("SCLC_1186", "Close time invalid rule"),
    TEST_REQUIRED_COEFFICIENT_OR_WEIGHT("SCLC_1187", "Test required coefficient or weight"),
    TEST_NOT_ALLOW_BOTH_COEFFICIENT_AND_WEIGHT("SCLC_1188", "Test not allow both coefficient and weight"),
    TEST_COEFFICIENT_INVALID("SCLC_1189", "Test coefficient invalid"),
    TEST_WEIGHT_INVALID("SCLC_1190", "Test weight invalid"),
    TEST_WEIGHT_EXCEED_MAX("SCLC_1191", "Test weight exceed max"),
    TEST_REQUIRED_WEIGHT("SCLC_1192", "Existed weight config. You do not config coefficient point"),
    TEST_REQUIRED_COEFFICIENT("SCLC_1193", "Existed coefficient config. You do not config weight point"),
    EXERCISE_NOT_ALLOW_SETTING("SCLC_1194", "Exercise not allow setting open_time, close_time, weight, coefficient"),
    EXERCISE_NOT_ALLOW_UPDATE_CATEGORY("SCLC_1195", "Exercise/test not allow update category"),
    TEST_INVALID_SETTING_DURATION_OR_OPEN_CLOSE_TIME("SCLC_1196", "Invalid setting close_time/open_time or duration"),
    CALCULATION_METHOD_INVALID("SCLC_1178", "Invalid calculation_method"),
    NOT_ALLOW_CHANGE_CALCULATION_METHOD("SCLC_1179", "Elearning was approved :not allow change calculation method"),
    NOT_ALLOW_CHANGE_PRIVACY("SCLC_1180", "Elearning was approved: not allow change privacy"),
    NOT_ALLOW_CHANGE_SUBJECT("SCLC_1181", "Elearning was approved: not allow change subject"),
    NOT_ALLOW_CHANGE_GRADE("SCLC_1182", "Elearning was approved: not allow change grade"),
    NOT_ALLOW_CHANGE_ALLOW_COMMENT("SCLC_1183", "Elearning was approved: not allow change allow comment"),
    NOT_ALLOW_CHANGE_FEE("SCLC_1184", "Elearning was approved: not allow change fee"),
    NOT_ALLOW_CHANGE_PRICE("SCLC_1185", "Elearning was approved: not allow change price"),
    NOT_ALLOW_CHANGE_ASSIGN_GROUP("SCLC_1186", "Elearning was approved: not allow change assign group/class"),
    // user help
    USER_HELP_NOT_FOUND("SCLC_1200", "User help not found"),
    USER_HELP_HAS_FEEDBACK("SCLC_1201", "You was sent feedback for this help"),

    NEWS_NOT_FOUND("SCLC_1230", "News not found"),
    ANNOUNCEMENT_ORG_NOT_FOUND("SCLC_1231", "Announcement not found"),
    INTRO_ORG_NOT_FOUND("SCLC_1232", "Intro not found"),
    LINK_WEB_ORG_NOT_FOUND("SCLC_1233", "Link web not found"),
    TIME_TABLE_ORG_NOT_FOUND("SCLC_1234", "Timetable not found"),
    ELEARNING_START_TIME_ENABLE_BEFORE("SCLC_1235", "Starttime_enable was setting before"),
    ELEARNING_START_TIME_BEFORE("SCLC_1236", "Start_time was setting before"),
    ELEARNING_END_TIME_ENABLE_BEFORE("SCLC_1237", "Endtime_enable was setting before"),
    ELEARNING_END_TIME_BEFORE("SCLC_1238", "End_time was setting before"),
    IMPORT_SEX_NOT_VALID("SCLC_1239", "Sex is not valid"),
    IMPORT_PHONE_NOT_VALID("SCLC_1240", "Phone is not valid"),
    IMPORT_BIRTHDAY_NOT_VALID("SCLC_1241", "Birthday is not valid"),
    IMPORT_EMAIL_NOT_VALID("SCLC_1242", "Email is not valid"),
    IMPORT_NOT_ALLOW_EXTENSION("SCLC_1243", "Not allow extension"),
    ELEARNING_NOT_ALLOW_COMMENT("SCLC_1244", "Elearning not allow comment"),
    ELEARNING_NOT_YET_BEGIN("SCLC_1245", "This elearning not yet begin"),
    NOT_ALLOW_EDIT_QUESTION_WHEN_HAVE_ANSWER("SCLC_1246", "Not allow edit content when the question have exist answer"),
    INVALID_CONTENT_LENGTH("SCLC_1247", "Invalid content length"),
    INTERACTIVE_ANSWER_NOT_FOUND("SCLC_1248", "Interactive answer not found or permission access denied"),
    INTERACTIVE_ANSWER_INVALID_CONTENT("SCLC_1249", "Interactive answer required content or image"),
    ELEARNING_FINISHED("SCLC_1250", "This elearning has finished"),
    INVALID_TYPE("SCLC_1251", "Invalid type"),
    FILE_NOT_FOUND("SCLC_1252", "File not found"),
    SCHOOL_ADMIN_CATEGORY_TYPE_NOT_SUPPORT("SCLC_1270", "Category type not support. Only support NEWS, ANNOUNCEMENT"),
    INVALID_ACTION_IMPORT("SCLC_1253", "Invalid action import . Only accept status file import is CHECKING"),
    INVALID_ACTION_IMPORT_COMPLETED("SCLC_1254", "Invalid action import . Only accept status file import is DRAFT"),
    CHECKING_AND_IMPORT_REQUIRED_THE_SAME("SCLC_1255", "Checking step and Import file step required the same method"),
    INVALID_ACTION_IMPORT_BEFORE("SCLC_1256", "Invalid action import. This file was import before"),
    NOTHING_VALID_RECORD_TO_IMPORT("SCLC_1257", "Nothing valid record to import"),
    FILE_IMPORT_INVALID("SCLC_1258", "File import invalid"),
    UNSUPPORT_METHOD_IMPORT_FILE("SCLC_1259", "Unsupport method import file"),
    SUBJECT_STATUS_INVALID("SCLC_1260", "Subject status invalid"),

    GRADE_LIST_INVALID("SCLC_1261", "Grade list invalid format"),

    SYSTEM_YEAR_NOT_FOUND("SCLC_1270", "System year not found or deleted"),
    SYSTEM_YEAR_WITH_TIME_HAS_EXISTED("SCLC_1271", "System year which has the same from time and to time has existed"),
    SYSTEM_YEAR_FROM_YEAR_AND_TO_YEAR_INVALID("SCLC_1272", "From year and to year invalid. from_year <= currentYear <= to_year"),
    SEMESTER_TIME_FORMAT_INVALID("SCLC_1273", "Time format invalid. Right format: yyyy-MM-dd HH:mm:ss"),
    SEMESTER_TIME_YEAR_INVALID("SCLC_1274", "Range time invalid. Year Of First Semester and Year Of End School Year must between from year and to year." +
            "First Semester Start Time less than Second Semester Start Time. Second Semester Start Time less than End School Year"),
    SCHOOL_YEAR_TO_YEAR_INVALID("SCLC_1275", "to_year invalid"),
    ADMIN_HAS_NOT_CREATED_SYSTEM_YEAR("SCLC_1276", "Admin has not created this system year. Please contact admin to get more info"),
    SCHOOL_YEAR_HAS_EXISTED("SCLC_1277", "School year has existed"),
    SCHOOL_YEAR_FROM_YEAR_INVALID("SCLC_1278", "from_year invalid"),
    FIRST_SEMESTER_START_MUST_LESS_THAN_SECOND_SEMESTER_START("SCLC_1279", "first_semester_start must less than second_semester_start"),
    SECOND_SEMESTER_START_MUST_LESS_THAN_END_SCHOOL_YEAR("SCLC_1280", "second_semester_start must less than end_school_year"),
    FROM_YEAR_MUST_LESS_OR_EQUAL_THAN_YEAR_OF_FIRST_SEMESTER_START("SCLC_1281", "year of first_semester_start must greater or equal than year of from_year"),
    TO_YEAR_MUST_GREATER_OR_EQUAL_THAN_YEAR_OF_END_SCHOOL_YEAR("SCLC_1282", "year of end_school_year must less or equal than to_year"),
    SCHOOL_SUBJECT_NOT_FOUND("SCLC_1283", "School subject not found or deleted"),
    SYSTEM_NOT_SUPPORT_DELETE_METHOD("SCLC_1284", "System not support delete method"),
    ADMIN_NOT_CREATE_ANY_SYSTEM_YEAR("SCLC_1285", "Admin not create any system year"),
    STAFF_DUTY_REQUIRED("SCLC_1286", "Staff duty required in staff"),
    SCHOOL_YEAR_REQUIRED("SCLC_1287", "School year required in staff"),
    SCHOOL_REQUIRED("SCLC_1287", "School required in staff"),

    TEACHER_HAS_BEEN_HOME_ROOM("SCLC_1300", "Teacher has been homeroom of other class in this schoolyear"),
    SUBJECT_HAS_BEEN_ASSIGNMENT_IN("SCLC_1301", "There are some subject has assignment with this teacher. Please check again"),
    TEACHER_HAS_NOT_ASSIGNMENT_ANY_SUBJECT("SCLC_1302", "Teacher has not assignment any subject"),
    NOT_SUPPORT_TO_GET_ORGANIZATION_BY_THIS_ROLE("SCLC_1303", "Not support get organization by this role"),
    IMPORT_SAMPLE_FILE_NOT_FOUND("SCLC_1304", "Import sample file not found"),

    TRANSFER_TYPE_INVALID("SCLC_1305", "Transfer type invalid"),
    TRANSFER_SCHOOL_REQUIRED("SCLC_1306", "Transfer school required"),
    TRANSFER_OUTSIDE_SCHOOL_REQUIRED("SCLC_1307", "Transfer outside school required"),
    TRANSFER_OUTSIDE_SCHOOL_INVALID("SCLC_1308", "Transfer outside school invalid"),
    TRANSFER_STAFF_NOT_FOUND("SCLC_1309", "Transfer staff not found"),
    STAFF_STATUS_NOT_ALLOW_CANCEL_TRANSFER("SCLC_1310", "Transfer staff status not allow"),
    TRANSFER_STAFF_INSIDE_COMPLETED_NOT_ALLOW_CANCEL("SCLC_1311", "Transfer staff inside was completed. Not allow cancel"),
    STATUS_NOT_ALLOW_TRANSFER_STAFF("SCLC_1312", "Cannot accepted transfer staff due status not allow"),
    CURRENT_SCHOOL_REQUIRED_SAME("SCLC_1313", "Current school required the same"),
    DESTINATION_SCHOOL_NOT_THE_SAME_CURRENT_SCHOOL("SCLC_1314", "Destination school not the same current school"),
    NOT_ALLOW_TRANSFER_STAFF_BECAUSE_STATUS_NOT_ALLOW("SCLC_1315", "Not allow transfer staff because status of staff not allow"),
    NOT_ALLOW_RECEIVED_TRANSFER_STAFF_BECAUSE_STATUS_NOT_ALLOW("SCLC_1316", "Not allow receive transfer staff because status of staff not allow"),
    NOT_ALLOW_RECEIVED_TRANSFER_STAFF_BECAUSE_APPROVED_BEFORE("SCLC_1317", "Not allow receive transfer staff because the staff was approved before"),
    NOT_ALLOW_REJECT_TRANSFER_STAFF_BECAUSE_STATUS_NOT_ALLOW("SCLC_1318", "Not allow reject transfer staff because status of staff not allow"),

    STAFF_NUMBER_EXIST("SCLC_1305", "Staff number existed in school! Please using another staff number "),
    STAFF_NUMBER_REQUIRED("SCLC_1306", "Staff number required"),
    STUDENT_NUMBER_REQUIRED("SCLC_1307", "Student number required"),
    STUDENT_CODE_REQUIRED("SCLC_1308", "Staff code required"),


    STUDENTS_HAS_NEW_INFO_IN_CURRENT_YEAR("SCLC_1320", "Some student was created new info in current schoolyear, can not transfer. Please check again"),
    GRADE_OF_NEXT_CLASS_MUST_EQUAL_GRADE_OF_OLD_CLASS("SCLC_1321", "Grade of next class must equal grade of old class. Please check again"),
    GRADE_OF_NEXT_CLASS_MUST_GREATER_1_THAN_GRADE_OF_OLD_CLASS("SCLC_1322", "Grade of next class must greater 1 than grade of old class. Please check again"),
    GRADE_OF_OLD_CLASS_MUST_HAVE_LEVEL_MAXIMUM("SCLC_1323", "Grade of old class must have level max. Please check again"),
    NOT_SUPPORT_TRANSFER_TYPE("SCLC_1324", "Not support transfer type"),
    NEW_GRADE_OF_SCHOOLYEAR_NOT_FOUND("SCLC_1325", "Grade of new schoolyear not found in previous schoolyear. Please check again"),

    ELEARNING_ENABLE_START_TIME_OR_ENABLE_END_TIME_REQUIRED_NOT_NULL("SCLC_1325", "Enable_start_time/enable_end_time required not null"),
    END_TIME_NOT_ALLOW_PUBLISH("SCLC_1326", "End time not enough to publish elearning"),
    CAN_NOT_FIND_ANY_PREVIOUS_SCHOOL_YEAR("SCLC_1325", "Can not find any previous schoolyear to clone data"),
    STAFF_NUMBER_EXISTED_IN_DESTINATION_SCHOOL("SCLC_1326", "Staff number existed in destination school"),
    SCHOOL_YEAR_NOT_EXISTED_DESTINATION_SCHOOL("SCLC_1327", "School year existed in destination school"),
    REQUIRED_DOC_OR_IMAGE_TYPE_IN_QUESTION("SCLC_1328", "Required doc or image type in question"),
    ANSWER_INVALID_FORMAT("SCLC_1329", "Answer invalid format. Required json type"),
    TRANSFER_STUDENT_NOT_FOUND("SCLC_1330", "Transfer student not found"),
    STUDENT_NUMBER_EXISTED_IN_DESTINATION_SCHOOL("SCLC_1331", "Student number existed in destination school"),
    NOT_ALLOW_RECEIVED_TRANSFER_STUDENT_BECAUSE_STATUS_NOT_ALLOW("SCLC_1332", "Not allow receive transfer student because status of student not allow"),
    STATUS_NOT_ALLOW_TRANSFER_STUDENT("SCLC_1333", "Cannot accepted transfer student due status not allow"),
    SCHOOL_YEAR_OF_CLASS_REQUIRED_SAME_SCHOOL_YEAR_DESTINATION("SCLC_1334", "School year of new class required same school year destination"),
    NOT_ALLOW_TRANSFER_STUDENT_BECAUSE_STATUS_NOT_ALLOW("SCLC_1335", "Not allow transfer student because status of student not allow"),
    NOT_ALLOW_CANCEL_TRANSFER_STUDENT_BECAUSE_STATUS_NOT_ALLOW("SCLC_1336", "Not allow cancel transfer student because status of student not allow"),
    NOT_ALLOW_RECEIVED_TRANSFER_STUDENT_BECAUSE_APPROVED_BEFORE("SCLC_1337", "Not allow receive transfer student because the student was approved before"),
    LESSON_UPLOAD_FAIL("SCLC_1338", "Some lesson upload not completed. Please check status upload some lesson"),
    CANNOT_DELETE_ELEARNING_SOME_ID_NOT_ALLOW("SCLC_1339", "Cannot delete elearning. Some elearning not allow :"),
    CANNOT_GET_BASE_BUCKET_NAME("SCLC_1340", "Cannot get base bucket name"),
    GROUP_NAME_EXIST("SCLC_1360", "Group name exist"),
    GROUP_STUDY_NOT_FOUND("SCLC_1361", "Group study not found or permission denied"),
    CANNOT_ADD_MEMBER_BECAUSE_SOME_USER_NOT_EXIST("SCLC_1362", "Cannot add member to group, because some user not exist:"),
    NOTHING_MEMBER_VALID_TO_ADD_GROUP("SCLC_1363", "Nothing member valid to add group"),
    GROUP_STUDY_MEMBER_NOT_FOUND("SCLC_1364", "Group study member not found or permission denied"),
    CANNOT_REMOVE_MEMBER_BECAUSE_SOME_MEMBER_NOT_EXIST("SCLC_1365", "Cannot remove member to group, because some member not exist:"),
    CANNOT_DELETE_GROUP_SOME_ID_NOT_ALLOW("SCLC_1366", "Cannot delete group. Some group not allow :"),
    STUDENT_WAS_DISABLED("SCLC_1350", "Student was disabled"),
    STUDENT_WAS_GRADUATE("SCLC_1351", "Some students was graduated"),

    QUESTION_BANK_NOT_FOUND("SCLC_1370", "Question bank not found or deleted"),
    QUESTION_BANK_TYPE_NOT_SUPPORTED("SCLC_1371", "Question bank type not supported, only support ESSAY | SINGLE_CHOICE | MULTIPLE_CHOICE | WORD_CHOICE | WORD_MATCH | YES_NO | FILL_IN_BLANK"),
    QUESTION_PARENT_TYPE_NOT_SUPPORTED("SCLC_1372", "Question parent type not supported, only support: BANK, TEST"),
    METHOD_CREATE_QUESTION_BANK_NOT_SUPPORTED("SCLC_1373", "Method create question not supported, only support: MANUAL, IMPORT, IPTEST"),
    QUESTION_CATEGORY_NOT_SUPPORTED("SCLC_1374", "Question category not supported, only support: CHOICE | ESSAY"),
    QUESTION_LEVEL_NOT_SUPPORTED("SCLC_1375", "Question level not supported, only support: EASY | MEDIUM | HARD"),
    QUESTION_TYPE_NOT_SUPPORTED("SCLC_1376", "Question type not supported, only support: ESSAY | SINGLE_CHOICE | MULTIPLE_CHOICE | WORD_CHOICE | WORD_MATCH | YES_NO | FILL_IN_BLANK"),
    MANUAL_IS_REQUIRED("SCLC_1377", "manual is required"),
    SUBMISSION_FORM_IS_REQUIRED("SCLC_1378", "submission_form is required"),
    SUBMISSION_FORM_NOT_SUPPORTED("SCLC_1379", "Submission form not supported, only support: MANUAL | UPLOAD | BOTH"),
    QUESTION_HAD_ANSWERED("SCLC_1380", "This question had answers. Can not create new"),
    CONTENT_QUESTION_WORD_CHOICE_WRONG_FORMAT("SCLC_1381", "content of question must have format: [a-zA-Z][answer1|answer2|...][a-zA-Z]"),
    QUESTION_MUST_HAVE_AT_LEAST_ONE_ANSWER("SCLC_1382", "Question with this type must have at least 1 answer"),
    METHOD_CREATE_QUESTION_TEST_NOT_SUPPORTED("SCLC_1383", "Method create question test not supported, only support: MANUAL, IMPORT, SELECTED, RANDOM, UPLOAD, IPTEST"),
    QUESTION_CATEGORY_INVALID("SCLC_1384", "Invalid category. If type in (ESSAY) then category is ESSAY. If type in (SINGLE_CHOICE | MULTIPLE_CHOICE | WORD_CHOICE | YES_NO | WORD_MATCH | FILL_IN_BLANK) then category is CHOICE"),
    QUESTION_BANK_NOT_HAVE_ANY_QUESTION("SCLC_1385", "Question bank not have any question"),
    TYPE_UPDATE_POSITION_NOT_SUPPORTED("SCLC_1386", "Type to update position not supported, only support: RANDOM | NULL"),
    IPTEST_IS_REQUIRED("SCLC_1387", "iptest is required"),
    TEST_ID_IPTEST_IS_REQUIRED("SCLC_1388", "iptest.test_id is required"),
    SELECT_QUESTION_ID_IS_REQUIRED("SCLC_1389", "select_question_id is required"),

    ANSWER_MUST_HAVE_ANSWER_MATCHING("SCLC_1390", "Answer not have any answer matching"),
    ANSWER_MATCHING_MISSING_REQUIRED_FIELDS("SCLC_1391", "answer.content, answer.name, answer.index"),
    ANSWER_MULTI_CHOICE_MISSING_REQUIRED_FIELDS("SCLC_1392", "answer.name, answer.selected í required"),
    ANSWER_MANUAL_REQUEST_MISSING_REQUIRED_FIELDS("SCLC_1393", "answer.name, answer.selected is required"),
    ANSWER_WORD_CHOICE_REQUEST_MISSING_REQUIRED_FIELDS("SCLC_1394", "answer.position, answer.selected is required"),
    ANSWER_SINGLE_CHOICE_REQUEST_MISSING_REQUIRED_FIELDS("SCLC_1395", "answer.name, answer.selected, answer.index is required"),
    ANSWER_MULTI_CHOICE_REQUEST_MISSING_REQUIRED_FIELDS("SCLC_1396", "answer.name, answer.selected is required"),

    CAN_NOT_CLONE_CHOICE_TEST_FROM_ESSAY_TEST("SCLC_1397", "Can not import question from test (type: CHOICE) to test (type: ESSAY)"),
    CAN_NOT_CLONE_ESSAY_TEST_FROM_CHOICE_TEST("SCLC_1398", "Can not import question from test (type: ESSAY) to test (type: CHOICE)"),
    CAN_NOT_IMPORT_ESSAY_QUESTION_TO_CHOICE_TEST("SCLC_1399", "Can not import ESSAY question to CHOICE test"),
    CAN_NOT_IMPORT_CHOICE_QUESTION_TO_ESSAY_TEST("SCLC_1400", "Can not import CHOICE question to ESSAY test "),

    IMPORT_QUESTION_COLUMN_NAME_FILE_INVALID("SCLC_1410", "Column name not same as file template. Please check again and re upload file"),
    IMPORT_QUESTION_IMPORT_FILE_KEY_NOT_FOUND("SCLC_1411", "Import file key not found"),
    QUESTION_CAN_NOT_ADD_TO_TEST("SCLC_1412", "Question can not add to test. Please check question category again. Example: testType = ESSAY -> questionCategory = ESSAY, testType = CHOICE -> questionCategory = CHOICE, testType = MIX -> questionCategory in [ESSAY, CHOICE]"),
    TYPE_NOT_SUPPORTED("SCLC_1413", "Type not supported, only support: RANDOM"),
    SYSTEM_NOT_SUPPORT_THIS_METHOD("SCLC_1414", "System not support this method. You only can re upload test"),


    NUMBER_OF_EASY_QUESTION_NOT_ENOUGH("SCLC_1420", "Number of easy questions in bank not enough. Please check again"),
    NUMBER_OF_MEDIUM_QUESTION_NOT_ENOUGH("SCLC_1421", "Number of medium questions in bank not enough. Please check again"),
    NUMBER_OF_HARD_QUESTION_NOT_ENOUGH("SCLC_1422", "Number of hard questions in bank not enough. Please check again"),
    PARENT_IS_REQUIRED("SLCL_1423", "parent is required"),
    PARENT_ID_IS_REQUIRED("SLCL_1424", "parent_id is required"),
    INDEX_IS_REQUIRED("SLCL_1425", "index is required"),
    METHOD_IS_REQUIRED("SLCL_1426", "method is required"),
    CATEGORY_IS_REQUIRED("SLCL_1427", "category is required"),
    TYPE_IS_REQUIRED("SLCL_1428", "type is required"),
    POINT_IS_REQUIRED("SLCL_1429", "point is required"),
    RANDOMS_IS_REQUIRED("SLCL_1430", "randoms is required"),
    QUESTION_IDS_IS_REQUIRED("SLCL_1431", "question_ids is required"),
    RANDOM_SETTING_NOT_FOUND("SLCL_1432", "random setting not found"),
    TEST_ID_IS_REQUIRED("SCLC_1433", "test_id is required"),
    QUESTION_ID_IS_REQUIRED("SLCL_1434", "question_id is required"),
    RANDOM_ID_IS_REQUIRED("SLCL_1435", "random_id is required"),
    METHOD_IS_REQUIRED_RANDOM_OR_MANUAL("SLCL_1436", "method is required. MANUAL | RANDOM | IPTEST"),
    RANDOMS_SETTING_IS_REQUIRED("SLCL_1437", "randoms.settings is required"),
    IDS_IS_REQUIRED("SCLC_1438", "ids is required"),
    ID_IS_RANDOM_ID("SCLC_1439", "id is random_id"),

    MIN_POINT_INVALID("SLCL_1440", "Minimum point of each question is 0.25. Please check number of question in the test."),
    CAN_NOT_UPDATE_POINT_FOR_QUESTION_CHOICE("SLCL_1441", "Can not update point for question with type is CHOICE"),
    CATEGORY_OF_QUESTION_BANK_NOT_FOUND("SLCL_1442", "randoms is required"),

    SUBJECT_REQUIRED_JSON_FORMAT("SLCL_1500", "subject_ids invalid format. Required json"),
    EXAM_NOT_FOUND("SLCL_1501", "Exam not found or permission access denied"),
    PRIVACY_NOT_VALID("SLCL_1502", "Privacy not valid"),
    REQUIRED_ASSIGN_IDS("SLCL_1503", "Required assign_ids"),
    NOT_ALLOW_ASSIGN_IDS("SLCL_1504", "Privacy not allow assign_ids"),
    CANNOT_ASSIGN_IDS_BECAUSE_SOME_ID_NOT_ALLOW("SLCL_1505", "Cannot assign class/group. Because some class/group not allow :"),
    PRIVACY_REQUIRED("SLCL_1505", "Privacy required"),
    EXAM_NOT_SETTING("SLCL_1506", "Exam is not setting"),
    EXAM_WAS_PUBLISH_DO_NOT_UPDATE_DELETE("SLCL_1507", "Exam was published, do not update or delete"),
    EXAM_GENERAL_NOT_VALID("SLCL_1508", "Exam general not valid"),
    EXAM_SETTING_NOT_VALID("SLCL_1509", "Exam setting not valid"),
    EXAM_TEST_NOT_VALID("SLCL_1510", "Exam test not valid .Id test invalid :"),
    EXAM_REQUIRED_AT_LEAST_ONE_VALID_TEST("SLCL_1511", "Exam required at least one valid test"),
    SCHOOL_ID_REQUIRED("SLCL_1512", "school_id required"),
    EXAM_STATUS_NOT_ALLOW_APRROVE("SLCL_1513", "Exam status not allow approve"),
    EXAM_STATUS_NOT_ALLOW_REJECT("SLCL_1514", "Exam status not allow reject"),
    REJECT_EXAM_REQUIRED_NOTE("SLCL_1515", "Reject exam required note"),
    NO_EXAM_TO_HIDE_OR_RESTORE("SLCL_1516", "No exam to stop/restore"),
    EXAM_STATUS_WAS_REQUEST_PUBLISH_BEFORE("SLCL_1517", "Exam status was request publish before"),
    EXPORT_TYPE_IS_REQUIRED("SLCL_1518", "Export type is required"),
    EXPORT_TYPE_IS_INVALID("SLCL_1519", "Export type is invalid"),
    STAFF_CODE_NOT_ALLOW_NULL("SLCL_1520", "Staff code not allow null"),
    STUDENT_CODE_NOT_ALLOW_NULL("SLCL_1521", "Student code not allow null"),
    YOU_ONLY_JOIN_EXAM_FREE("SLCL_1522", "You only join exam free. Exam have fee required buy"),
    CANNOT_PARSE_ASSIGN_IDS("SLCL_1523", "Cannot parse assign ids"),
    ASSIGN_CLASS_NOT_ALLOW_THIS_STUDENT_JOIN("SLCL_1524", "Assign class not allow this student join"),
    ASSIGN_GROUP_NOT_ALLOW_THIS_STUDENT_JOIN("SLCL_1525", "Assign group not allow this student join"),
    USER_EXAM_NOT_FOUND("SLCL_1526", "User exam not found or permission access denied"),
    USER_JOIN_EXAM_BEFORE("SLCL_1527", "You joined this exam before"),
    EXAM_NO_PUBLISH_NOT_ALLOW_JOIN("SLCL_1528", "Exam no publish. Not allow join"),
    UNSUPPORT_EXPORT_FORMAT("SLCL_1529", "Unsupport export format file"),
    ERROR_EXPORT_FILE("SLCL_1530", "Have error occur when export file. Please try again later"),
    NO_DATA_TO_EXPORT("SLCL_1531", "No data record to export file"),
    REQUIRED_FEE("SLCL_1532", "Required fee"),
    LIMIT_INVALID("SLCL_1533", "Limit invalid"),
    EXAM_NO_PUBLISH_NOT_ALLOW_LIKE("SLCL_1534", "Exam no publish. Not allow like or unlike"),
    CANNOT_AUTO_GENEATE_USER("SLCL_1535", "Cannot generate new users"),
    ELEARNING_PRIVATE_REQUIRED_ASSIGN_GROUP_OR_CLASS("SLCL_1536", "Elearning private required assign group or class"),
    ELEARNING_ASSIGN_GROUP_INVALID_FORMAT("SLCL_1537", "Assign group invalid format. Required json"),
    ELEARNING_ASSIGN_CLASS_INVALID_FORMAT("SLCL_1538", "Assign class invalid format. Required json"),
    NOTHING_CLASS_OR_GROUP_VALID_TO_ASSIGN("SLCL_1539", "Nothing class or group valid to assign"),
    NOT_ALLOW_ASSIGN_FOR_BOTH_ELEARNING_AND_GROUP("SLCL_1540", "Not allow assign for both elearning and group"),
    LESSON_NOT_IN_ELEARNING("SLCL_1541", "Lesson not in elearning"),
    CANNOT_DELETE_DOC_SOME_ID_NOT_ALLOW("SCLC_1542", "Cannot delete doc. Some doc not allow:"),
    CANNOT_DELETE_DOC_SOME_ID_WAS_USED("SCLC_1543", "Cannot delete doc. Some doc was used:"),
    CANNOT_DELETE_DOC("SCLC_1544", "Cannot delete doc. You do not permission or your doc not exist"),
    SUBJECT_ID_CONFLICT_WITH_SUBJECT_ID_OF_ELAEARNING("SCLC_1545", "Subject id param conflict with subject_id in elearning"),
    CANNOT_ALLOW_SEARCH_CLASS_AND_GROUP("SCLC_1546", "Cannot allow class_id and group_id same not null"),
    STAFF_CODE_EXISTED("SCLC_1547", "Staff code existed"),
    STAFF_NUMBER_EXISTED("SCLC_1548", "Staff number existed"),
    STUDENT_CODE_EXISTED("SCLC_1549", "Student code existed"),
    STUDENT_NUMBER_EXISTED("SCLC_1550", "Student number existed"),
    REQUIRED_SUBJECT("SCLC_1551", "Required subject_id"),
    STAFF_CODE_REQUIRED("SCLC_1552", "Staff code required"),

    USER_NOT_LINK_ACCOUNT("SLCL_1600", "User not linked any account teacher"),
    QUESTION_NOT_FOUND_IN_ANY_TEST("SCLC_1601", "Question not found in any test"),
    NOT_UPDATE_POINT_FOR_QUESTION_WITH_CATEGORY_IS_CHOICE("SCLC_1602", "Question have category is CHOICE. Can not update point"),
    TEST_WAS_USED_CAN_NOT_ADD_OR_MODIFY_QUESTION("SCLC_1603", "Test was used, can not add or modify question"),
    TEST_NOT_HAVE_ANY_QUESTION_TO_IMPORT("SCLC_1604", "Test don't have any question to import"),

    ESSAY_POINT_MUST_LESS_THAN_TOTAL_POINT_OF_TEST("SLCL_1620", "Total essay point must less than total point of test"),
    ESSAY_POINT_MUST_LESS_OR_EQUAL_THAN_TOTAL_POINT_OF_TEST("SLCL_1621", "Total essay point must less or equal than total point of test"),
    QUESTION_FILL_IN_BLANK_MUST_HAVE_AT_LEAST_TWO_ANSWER("SCLC_1622", "Question must have at least 1 answer in each []"),
    ANSWERS_REQUIRED("SCLC_1623", "answers is required"),
    CONTENT_REQUIRED("SCLC_1624", "content is required"),
    QUESTION_SELECT_DUPLICATE("SCLC_1625", "question_select_id must different than question_id"),


    PRODUCT_IS_REQUIRED("SCLC_1640", "product is required"),
    PRODUCT_ID_IS_REQUIRED("SCLC_1641", "product_id is required"),
    PRODUCT_IS_NOT_SUPPORT("SCLC_1642", "product is not support. Only support type: ELEARNING, EXAM"),
    ELEARNING_ID_IS_REQUIRED("SCLC_1643", "elearning_id is required"),
    EXAM_WAS_ADD("SCLC_1644", "Exam was add to cart"),
    EXAM_WAS_BOUGHT("SCLC_1645", "Exam was bought before"),
    QUESTION_MUST_HAVE_AT_LEAST_TWO_ANSWER("SCLC_1382", "Question with this type must have at least 2 answer"),
    NOT_ALLOW_QUIT_STAFF_BECAUSE_STATUS_NOT_ALLOW("SCLC_1646", "Not allow make staff to quit because status of staff not allow"),
    NOT_ALLOW_RESTORE_STAFF_BECAUSE_STATUS_NOT_ALLOW("SCLC_1647", "Not allow restore staff because status of staff not allow"),
    QUESTION_MUST_HAVE_ONE_RIGHT_SELECTION("SCLC_1383", "Question must have only one right selection"),
    QUESTION_MUST_HAVE_ONE_OR_MORE_RIGHT_SELECTION("SCLC_1383", "Question must have one or more right selection"),
    ATTACHMENTS_IS_REQUIRED("SCLC_1384", "Attachments is required"),


    NAME_IS_REQUIRED("SCLC_1400", "Name is required"),
    ONLINE_CLASS_NOT_ASSIGNED("SCLC_1401", "You must add at least elearning_id, or assign_group_ids or assign_class_ids"),
    ENABLE_IS_REQUIRED("SCLC_1402", "Enable is required"),
    GROUP_STUDY_HAVE_MAXIMUM_ONE_ONLINE_CLASS("SCLC_1403", "Chỉ tạo được nhiều nhất một phòng học mỗi nhóm. Vui lòng chọn lại"), //Group had online class. You only can create maximum 1 online class in each group
    CLASS_STUDY_HAVE_MAXIMUM_ONE_ONLINE_CLASS("SCLC_1404", "Chỉ tạo được nhiều nhất một phòng học mỗi lớp. Vui lòng chọn lại"),
    ID_IS_REQUIRED("SCLC_1405", "id is required"),
    GROUP_HAVE_MAXIMUM_ONE_ONLINE_CLASS("SCLC_1406", "Chỉ tạo được nhiều nhất một phòng học mỗi nhóm. Vui lòng chọn lại"),
    CLASS_HAVE_MAXIMUM_ONE_ONLINE_CLASS("SCLC_1407", "Chỉ tạo được nhiều nhất một phòng học mỗi lớp. Vui lòng chọn lại"),
    ASSIGNMENT_TYPE_IS_REQUIRED("SCLC_1408", "Assignment type is required"),
    ASSIGNMENT_TYPE_NOT_SUPPORTED("SCLC_1409", "Assignment type is not supported. Only support: ELEARNING | GROUP | CLASS"),
    GROUP_IDS_IS_REQUIRED("SCLC_1410", "group_ids is required"),
    CLASS_IDS_IS_REQUIRED("SCLC_1411", "class_ids is required"),
    DUPLICATE_SCHEDULE_TEACHER_IN_2_ONLINE_CLASS("SCLC_1412", "Buổi học vào {lesson_time_1} tại phòng học online {online_class_name_1} do thầy {teacher_name_1} đã bị trùng thời gian với buổi học {lesson_time_2} do thầy {teacher_name_2} tạo trong phòng học online {online_class_name_2}. Vui lòng kiểm tra lại"),
    DUPLICATE_SCHEDULE_TEACHER_IN_1_ONLINE_CLASS("SCLC_1413", "Buổi học vào {lesson_time_1} đã bị trùng thời gian với buổi học {lesson_time_2}. Vui lòng kiểm tra lại"),
    NOT_HAVE_PERMISSION_TO_ASSIGN_ANY_TEACHER("SCLC_1414", "Bạn không có quyền thêm lịch cho các giáo viên khác"),
    CLASS_IDS_AND_GROUP_IDS_IS_REQUIRED("SCLC_1415", "class_ids and group_ids is required"),

    NUMBER_OF_QUESTION_NOT_ENOUGH("SCLC_1422", "Number of questions in bank not enough. Please check again"),

    // error nghiep vu moi online class
    LESSON_ID_IS_REQUIRED("SLCL_1450", "lesson_id is required"),
    REQUEST_TYPE_NOT_SUPPORTED("SLCL_1451", "request type not supported. Only support: CHANGE | EDIT | CANCEL"),
    EDIT_LESSON_IS_REQUIRED("SLCL_1452", "edit_lesson is required"),
    EDIT_LESSON_DATE_IS_REQUIRED("SLCL_1453", "edit_lesson.date is required"),
    EDIT_LESSON_DURATION_IS_REQUIRED("SLCL_1454", "edit_lesson.duration is required"),
    EDIT_LESSON_START_IS_REQUIRED("SLCL_1455", "edit_lesson.start is required"),
    EDIT_LESSON_START_IS_INVALID_FORMAT("SLCL_1456", "edit_lesson.start is invalid format. Correct format: hh:mm a"),
    DAY_OF_WEEK_NOT_SUPPORTED("SLCL_1457", "day of week not supported. Only support: MON | TUE | WED | THU | FRI | SAT | SUN"),
    CHANGE_LESSON_ID_IS_REQUIRED("SLCL_1458", "change_lesson_id is required"),
    LESSON_IS_FINISHED("SLCL_1459", "Lesson is finished, can not modify"),
    LESSON_IS_STREAMING("SLCL_1460", "Lesson is streaming, can not modify"),
    LESSON_CHANGE_IS_FINISHED("SLCL_1461", "Lesson change is finished, can not modify"),
    LESSON_CHANGE_IS_STREAMING("SLCL_1462", "Lesson change is streaming, can not modify"),
    CAN_NOT_CHANGE_LESSON_YOUR_SELF("SLCL_1463", "Lesson change is assigned to you before, can not requets change"),
    EDIT_LESSON_DATE_IS_INVALID_FORMAT("SLCL_1464", "edit_lesson.date is invalid format. Correct format: yyyy-MM-dd"),
    REQUEST_ID_IS_REQUIRED("SLCL_1465", "request_id is required"),
    PROCESS_IS_REQUIRED("SLCL_1466", "process is required"),
    PROCESS_NOT_SUPPORTED("SLCL_1467", "process not supported. Only support: 1: approved, -1: reject"),
    REQUEST_NOT_FOUND("SLCL_1468", "request not found"),
    REQUEST_WAS_APPROVED("SLCL_1469", "request was approved"),
    REQUEST_WAS_REJECT("SLCL_1470", "request was reject"),
    LESSON_IS_CANCELED("SLCL_1471", "Lesson is canceled, can not modify"),
    LESSON_CHANGE_IS_CANCELED("SLCL_1472", "Lesson change is canceled, can not modify"),
    LESSON_HAS_REQUEST_BEFORE("SLCL_1473", "Lesson has request pending before. Can not create new request"),
    REQUEST_HAS_APPROVED("SLCL_1474", "Request has approved. Can not cancel"),
    REQUEST_HAS_REJECT("SLCL_1475", "Request has reject. Can not cancel"),
    CAN_NOT_CREATE_REQUEST_SCHEDULE_OF_YOUR_ONLINE_CLASS("SLCL_1476", "This lesson belong to your online class. Can not create new request"),
    FEE_TYPE_IS_REQUIRED("SCLC_1477", "fee_type is required"),
    FEE_TYPE_IS_NOT_SUPPORTED("SCLC_1478", "fee_type is not supported. Only support: LESSON | COURSE"),
    ONLINE_CLASS_ID_IS_REQUIRED("SCLC_1479", "online_class_id is required"),
    SCHEDULE_ID_IS_REQUIRED("SCLC_1480", "schedule_id is required"),
    SCHEDULE_NOT_FOUND("SCLC_1481", "schedule not found"),

    ;

    private final String value;
    private final String reasonPhrase;

    ErrorCode(String value, String reasonPhrase) {
        this.value = value;
        this.reasonPhrase = reasonPhrase;
    }

    public String getCode() {
        return this.value;
    }

    public String getMessage() {
        return this.reasonPhrase;
    }

    @Override
    public String toString() {
        return "ErrorCode{" +
                "value='" + value + '\'' +
                ", reasonPhrase='" + reasonPhrase + '\'' +
                '}';
    }
}
